### ISSUE TITLE
CDS 5 - MTA Build fails

### ISSUE THREAD

**Issue by sedacrivity** [sapmentors/cap-community#105]
When using build command 'mbt build' for generating MTA I am getting the following error using CDS 5 ( works fine with CDS 4 ):

...
[cds] - done > wrote output to:
  gen/srv/srv/csn.json

[INTERNAL ERROR] TypeError: x.startsWith is not a function
    at _builtin (/home/xxx/node_modules/@sap/cds/lib/core/reflect.js:114:37)
    at _resolve (/home/xxx/node_modules/@sap/cds/lib/core/reflect.js:32:46)
    at _link (/home/xxx/node_modules/@sap/cds/lib/core/reflect.js:20:49)
    at _link (/home/xxx/node_modules/@sap/cds/lib/core/reflect.js:16:34)
    at new LinkedCSN (/home/xxx/node_modules/@sap/cds/lib/core/reflect.js:7:53)
    at cds.module.exports [as reflect] (/home/xxx/node_modules/@sap/cds/lib/core/reflect.js:126:46)
    at _getJournalEntityNames (/home/xxx/node_modules/@sap/cds/bin/build/hana/2migration.js:132:36)
    at module.exports (/home/xxx/node_modules/@sap/cds/bin/build/hana/2migration.js:11:30)
    at HanaModuleBuilder._compileToHdbmigration (/home/xxx/node_modules/@sap/cds/bin/build/hana/index.js:248:41)
    at async HanaModuleBuilder._compileToHana (/home/xxx/node_modules/@sap/cds/bin/build/hana/index.js:210:13)
Please report this error.

**Comment by gregorwolf** [comment]
Hi @sedacrivity ,
if you're using CAP in a real project please raise the incident via SAP Support or ask the question in the SAP Community.
Best regards
Gregor

**Comment by sedacrivity** [comment]
@gregorwolf It states on this page to do it here if you don't have a SAP customer number ?

**Comment by sedacrivity** [comment]
https://answers.sap.com/questions/13341630/sap-cds5-cannot-build-mta.html
