### ISSUE TITLE
Issues installing @sap/cds-dk on Windows 10

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cap-community#60]
Hello CAP Team,

as the issues reported about the installation of  @sap/cds-dk on Windows  in the CAP OpenSAP course increase I create this issue to track the topic better. I've just also tried to install @sap/cds-dk on my Windows 10 system with this release:

![Screenshot 2020-04-23 at 07 50 56](https://user-images.githubusercontent.com/2639535/80063872-2ba2b380-8537-11ea-98b2-721491b16dc1.png)

I've used the following command:

```
C:\Users\Gregor>npm rm -g @sap/cds

npm WARN deprecated undefined@0.1.0: this package has been deprecated
removed 69 packages in 1.063s

C:\Users\Gregor>npm i -g @sap/cds-dk
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

> @sap/cds-dk@1.7.1 preinstall C:\Users\Gregor\AppData\Roaming\npm\node_modules\@sap\cds-dk
> node ./lib/util/preinstall.js


The command 'cds' has moved from library @sap/cds to @sap/cds-dk.
It is recommended to remove the global version of @sap/cds and
reinstall @sap/cds-dk via
    npm rm -g @sap/cds
    npm i -g @sap/cds-dk

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\@sap\cds-dk\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @sap/cds-dk@1.7.1 preinstall: `node ./lib/util/preinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @sap/cds-dk@1.7.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gregor\AppData\Roaming\npm-cache\_logs\2020-04-23T05_39_29_058Z-debug.log
```

at the end of the debug.log file I see this errors:

```
6998 verbose stack Error: @sap/cds-dk@1.7.1 preinstall: `node ./lib/util/preinstall.js`
6998 verbose stack Exit status 1
6998 verbose stack     at EventEmitter.<anonymous> (C:\Users\Gregor\AppData\Roaming\nvm\v12.16.1\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
6998 verbose stack     at EventEmitter.emit (events.js:311:20)
6998 verbose stack     at ChildProcess.<anonymous> (C:\Users\Gregor\AppData\Roaming\nvm\v12.16.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
6998 verbose stack     at ChildProcess.emit (events.js:311:20)
6998 verbose stack     at maybeClose (internal/child_process.js:1021:16)
6998 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
6999 verbose pkgid @sap/cds-dk@1.7.1
7000 verbose cwd C:\Users\Gregor
7001 verbose Windows_NT 10.0.17763
7002 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "@sap/cds-dk"
7003 verbose node v12.16.1
7004 verbose npm  v6.13.4
7005 error code ELIFECYCLE
7006 error errno 1
7007 error @sap/cds-dk@1.7.1 preinstall: `node ./lib/util/preinstall.js`
7007 error Exit status 1
7008 error Failed at the @sap/cds-dk@1.7.1 preinstall script.
7008 error This is probably not a problem with npm. There is likely additional logging output above.
7009 verbose exit [ 1, true ]
```

hope that someone who can fix this issue can also replicate it and provide a fixed version.

CU
Gregor

**Comment by joergmann** [comment]
Hi @gregorwolf 

first of all thanks for the detailed error description.
It looks like @sap/cds has not been removed correctly.
Could you run the following command?
````bash
npm list -g -depth 0
`````
It should not list @sap/cds.

And also list the content of 
````
dir C:\Users\Gregor\AppData\Roaming\npm\node_modules\@sap\cds
````
If the above folder exists, delete it and rerun the installation.

Thanks
Jörg

**Comment by gregorwolf** [comment]
Thank you @joergmann, I've fixed the problem by deleting everything in C:\Users\Gregor\AppData\Roaming\npm\node_modules and removing the cds* files in C:\Users\Gregor\AppData\Roaming\npm\
